In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df_data = pd.read_csv('data/AA_data.csv')

In [5]:
sorted_df = df_data.sort_values('popularity', ascending = False).head(100)
sorted_df.head()

,Unnamed: 0,name,album,artist,release_date,length,popularity,danceability,acousticness,danceability.1,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature
23,23,SLOW DANCING IN THE DARK,BALLADS 1,Joji,2018-10-26,209273,87,0.515,0.5440,0.515,0.479,0.005980,0.191,-7.458,0.0261,88.964,4
24,24,Promiscuous,Loose,Nelly Furtado,2006-01-01,242293,86,0.808,0.0569,0.808,0.970,0.000061,0.154,-6.098,0.0506,114.328,4
20,20,The Way Life Goes (feat. Oh Wonder),Luv Is Rage 2,Lil Uzi Vert,2017-08-25,221746,84,0.703,0.6170,0.703,0.757,0.000000,0.106,-3.612,0.0500,82.008,4
19,19,Here Comes The Sun - Remastered 2009,Abbey Road (Remastered),The Beatles,1969-09-26,185733,84,0.557,0.0339,0.557,0.540,0.002480,0.179,-10.484,0.0347,129.171,4
63,63,EARFQUAKE,IGOR,"Tyler, The Creator",2019-05-17,190066,84,0.554,0.2300,0.554,0.498,0.000006,0.795,-8.866,0.0685,79.635,4

In [6]:
labels = list(sorted_df_1)[:]
features = sorted_df_1.mean().tolist()
features_all = sorted_two_df.mean().tolist()

angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)
fig = plt.figure(figsize = (18,18))

ax = fig.add_subplot(221, polar=True)
ax.plot(angles, features, 'o-', linewidth=2, label = "Popular", color= 'blue')
ax.fill(angles, features, alpha=0.25, facecolor='blue')
ax.set_thetagrids(angles * 180/np.pi, labels , fontsize = 13)


ax.set_rlabel_position(250)
plt.yticks([0.1 , 0.2 , 0.3 , 0.4, 0.5,  0.6, 0.7], ["0.1",'0.2', "0.3", "0.4", "0.5", "0.6", '0.7'  ], size=12)
plt.ylim(0,0.7)

ax.plot(angles, features_all, 'o-', linewidth=2, label = "All the Dataset", color= 'orange')
ax.fill(angles, features_all, alpha=0.25, facecolor='orange')
ax.set_title('Mean Values')
ax.grid(True)

plt.legend(loc='best', bbox_to_anchor=(0.1, 0.1))

NameError: name 'sorted_df_1' is not defined